// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data;

#nullable disable

namespace projekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230623110419_test")]
    partial class test
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("projekt.Models.Dania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NazwaDania")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dania");
                });

            modelBuilder.Entity("projekt.Models.DaniaProdukty", b =>
                {
                    b.Property<int>("IdProduktu")
                        .HasColumnType("int");

                    b.Property<int>("IdDania")
                        .HasColumnType("int");

                    b.Property<int>("Ilość")
                        .HasColumnType("int");

                    b.HasKey("IdProduktu", "IdDania");

                    b.HasIndex("IdDania");

                    b.ToTable("DaniaProdukty");
                });

            modelBuilder.Entity("projekt.Models.Jadlospis", b =>
                {
                    b.Property<int>("IdDania")
                        .HasColumnType("int");

                    b.Property<int>("IdKonta")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Dzień")
                        .HasColumnType("date");

                    b.HasKey("IdDania", "IdKonta");

                    b.HasIndex("IdKonta");

                    b.ToTable("Jadlospisy");
                });

            modelBuilder.Entity("projekt.Models.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("projekt.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float?>("Białko")
                        .HasMaxLength(6)
                        .HasColumnType("float");

                    b.Property<float?>("Błonnik")
                        .HasMaxLength(7)
                        .HasColumnType("float");

                    b.Property<float?>("Kaloryczność")
                        .HasMaxLength(12)
                        .HasColumnType("float");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(61)
                        .HasColumnType("varchar(61)");

                    b.Property<float?>("Tłuszcz")
                        .HasMaxLength(7)
                        .HasColumnType("float");

                    b.Property<float?>("Węglowodany")
                        .HasMaxLength(11)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Produkty");
                });

            modelBuilder.Entity("projekt.Models.DaniaProdukty", b =>
                {
                    b.HasOne("projekt.Models.Dania", "Dania")
                        .WithMany("DaniaProdukty")
                        .HasForeignKey("IdDania")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projekt.Models.Produkt", "Produkty")
                        .WithMany("DaniaProdukty")
                        .HasForeignKey("IdProduktu")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dania");

                    b.Navigation("Produkty");
                });

            modelBuilder.Entity("projekt.Models.Jadlospis", b =>
                {
                    b.HasOne("projekt.Models.Dania", "Dania")
                        .WithMany("Jadlospisy")
                        .HasForeignKey("IdDania")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projekt.Models.Konto", "Konta")
                        .WithMany("Jadlospisy")
                        .HasForeignKey("IdKonta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dania");

                    b.Navigation("Konta");
                });

            modelBuilder.Entity("projekt.Models.Dania", b =>
                {
                    b.Navigation("DaniaProdukty");

                    b.Navigation("Jadlospisy");
                });

            modelBuilder.Entity("projekt.Models.Konto", b =>
                {
                    b.Navigation("Jadlospisy");
                });

            modelBuilder.Entity("projekt.Models.Produkt", b =>
                {
                    b.Navigation("DaniaProdukty");
                });
#pragma warning restore 612, 618
        }
    }
}
