// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data;

#nullable disable

namespace projekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230529142304_dodanieKont")]
    partial class dodanieKont
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("projekt.Models.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Konta");
                });

            modelBuilder.Entity("projekt.Models.Produkt", b =>
                {
                    b.Property<int>("ID_Produktu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Białko")
                        .HasMaxLength(6)
                        .HasColumnType("varchar(6)");

                    b.Property<string>("Błonnik")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Kaloryczność")
                        .HasMaxLength(12)
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(61)
                        .HasColumnType("varchar(61)");

                    b.Property<string>("Tłuszcz")
                        .HasMaxLength(7)
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Węglowodany")
                        .HasMaxLength(11)
                        .HasColumnType("varchar(11)");

                    b.HasKey("ID_Produktu");

                    b.ToTable("Produkty");
                });
#pragma warning restore 612, 618
        }
    }
}
