// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Projekt.Data;

#nullable disable

namespace projekt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("projekt.Models.Dania", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NazwaDania")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Dania", (string)null);
                });

            modelBuilder.Entity("projekt.Models.DaniaProdukty", b =>
                {
                    b.Property<int>("IdDania")
                        .HasColumnType("int");

                    b.Property<int>("IdProduktu")
                        .HasColumnType("int");

                    b.Property<int>("Ilość")
                        .HasColumnType("int");

                    b.ToTable("DaniaProdukty", (string)null);
                });

            modelBuilder.Entity("projekt.Models.Konto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Haslo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Konta", (string)null);
                });

            modelBuilder.Entity("projekt.Models.Produkt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float?>("Białko")
                        .HasMaxLength(6)
                        .HasColumnType("float");

                    b.Property<float?>("Błonnik")
                        .HasMaxLength(7)
                        .HasColumnType("float");

                    b.Property<float?>("Kaloryczność")
                        .HasMaxLength(12)
                        .HasColumnType("float");

                    b.Property<string>("Nazwa")
                        .HasMaxLength(61)
                        .HasColumnType("varchar(61)");

                    b.Property<float?>("Tłuszcz")
                        .HasMaxLength(7)
                        .HasColumnType("float");

                    b.Property<float?>("Węglowodany")
                        .HasMaxLength(11)
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Produkty", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
